### ISSUE TITLE
64.zip was updated with newer point releases but the script was not updated to reflect.

### ISSUE THREAD

**Issue by polliard** [saltstack/salt-windows-dev#1]
Seriously.... :(.

If you update the zip, you must update the script that references it.

**Comment by polliard** [comment]
Apparently additional stuff was pulled out as well.  The vcredist_x64.exe vcredist_x64_mfs_update.exe and the VC for Python.....

**Comment by twangboy** [comment]
the files that were removed don't seem to be needed as long as you're not compiling anything. All the python modules in the zip file are pre-compiled for their version of windows, so they don't need the compiler. If you need to install additional modules that require a compiler, then you'll need to install the VC++ Compiler for Python separately.

That was my fault on the discrepancy between the version of the dev_env.ps1 script and the zip files. I pushed that up to my clone and failed to merge the pull request on Friday.

Please remember this is very much in the testing phases to make sure we've included everything we need in the dev environment. If we find out through our testing that some of these modules are actually needed, we'll add them back in.

Did you find an instance where the VC++ Compiler for Python needs to be in the dev script?

**Comment by polliard** [comment]
Not on the lastest build process and salt 2015.2 release.....
