### ISSUE TITLE
vcredist_x64.exe dependency missing

### ISSUE THREAD

**Issue by obestwalter** [saltstack/salt-windows-dev#11]
I ran the script on a clean Windows Server 2008 R2 and it borked over the infamous incorrect side by side configuration due to a missing vb runtime.

Installing [Microsoft Visual C++ 2008 Redistributable Package (x64)](https://www.microsoft.com/de-de/download/details.aspx?id=15336) solves the problem.

Is this a documentation bug as you can't bundle vcredist with the dependencies due to legal stuff or is it an oversight?
#### Error

> Installing get-pip.py . . .
> 
> Start-Process : This command cannot be executed due to the error: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
> [... and so on]

**Comment by twangboy** [comment]
This puzzles me because I haven't needed the VCRedist for any of the builds I've made using this script. I needed it in the past when pip or easy_install needed to compile something. I started using whl and other precompiled packages and haven't needed to install the VCRedist.

**Comment by obestwalter** [comment]
> I started using whl and other precompiled packages and haven't needed to install the VCRedist.

Are you sure it was not installed already? Just asking the obvious to make sure :) All I can say is that I used a fresh w2k8r2 install and ran the scripts unchanged and got that error.

As we are already in the process of creating a reproducable and completely automated way of setting up development and testing machines, I would say let's just forget about this problem till the vagrant approach is working.

**Comment by twangboy** [comment]
I think its a part of pywin32. You can see a bunch of the .dll's in `C:\salt\bin\Lib\site-packages\pythonwin`

**Comment by obestwalter** [comment]
I just ran into the same problem, when I was testing another salt bug on a fresh w2k8-r2 install. 
I am really getting a bit frustrated about this, because I start to feel I am doing things fundamentally wrong, but I really don't think so. 

So please correct me if I am wrong - but this is my expectation:

```
1. Take a fresh Windows installation
2. Install Salt 2015.5.0-2 (and nothing else)
3. open cmd.exe
4. type in 'salt-call --version' and get a result
```

But this doesn't work, because a) `c:\salt` is not in the path and b) if I call `c:\salt\salt-call --version`get the original error, I opened this bug here for.

What I have to do manually (and really think I shouldn't)
1. add `c:\salt` to the path
2. Install vcredist_x64

The DLL(s) coming with vcredist are actually not a direct salt dependency, but Python 2.6+ has this dependency on Windows if I understand these links correct.

http://stackoverflow.com/a/9047164/2626627
http://magiksys.blogspot.de/2013/03/python-27-winpe-vcredist-msvcr90dll.html

... so it is simple: salt will not work without this runtime installed, because Python won't work. Neither the development version nor the production version.

Amiright?

**Comment by obestwalter** [comment]
I guess we will never know and it really doesn't matter anymore :)
