### ISSUE TITLE
Make this work with Vagrant

### ISSUE THREAD

**Issue by obestwalter** [saltstack/salt-windows-dev#12]
I really appreciate the existence of this repo as a good starting point to develop and test salt on the Windows platform. 

How about making the last step and wrap all this into a vagrant configuration to obtain an automatically reproducable windows development and test environment? If a dev wanted to run their code changes against windows, all they had to do then is say something like

`SALT_PATH=<path to devs salt clone> vagrant up salt-windev` 

and they are good to go.

This would be a big step towards having an automaticlly installable test environment for the Windows platform to make progress with https://github.com/saltstack/salt/issues/20239
### things to be sorted out
- download and installation of vcredist (see #11) if it can't be integrated into `dev_env.ps1`
- map salt code from developer host into vagrant (e.g. via ENV like in example above)
- call `pip install --editable c:/<mapped salt code>` to have an editable installation

**Comment by obestwalter** [comment]
The only thing I am unsure of is, if it is legally o.k. to use a windows evalution version as basis for a vagrant windows box that could be shared then in the vagrant-cloud.

**Comment by obestwalter** [comment]
FYI: I started integrating it with vagrant [here](https://github.com/obestwalter/salt-windows-dev).

**Comment by twangboy** [comment]
I'm sorry. I'm very much a Vagrant novice. Where does this SALT-PATH variable go?

**Comment by obestwalter** [comment]
> I'm sorry. I'm very much a Vagrant novice. Where does this SALT-PATH variable go?

That was just me thinking loud. But the general idea is that you set an environment variable on your Linux host to pass the system specific information to vagrant (which at the moment is only the path to your salt clone in the Linux host). You can see how it works exactly now in the [README](https://github.com/obestwalter/salt-windows-dev) of my fork. 

It's not quite there yet though and I will still need a while get it to work reliably. Windows is just a very tricky beast and vagrant has similar problems with Windows like salt at the moment, so there is alot of duct tape involved to get these things to work at the current state.

If you are cool with getting this merged I would appreciate your input on the salt and windows specific bits of it, as I am very at home with Vagrant and Linux, but I am quite new to automation on Windows. So if we could work together on this, that would be great and I think we can get something off the ground in the nextweeks that could be used as a portable development environment and double as test platform for Windows CI tests, as outlined [here](https://trello.com/c/ng2qlrxm/3-overview).

Are you aware of the discussion [here](https://github.com/saltstack/salt/issues/20239#issuecomment-103100041)? I contacted @UtahDave about this also and he likes the idea as well to do CI with the help of vagrant images that run the windows tests. So maybe we should pull the discussion surrounding the implementation part of this here?

I am very willing to invest my time in this over the course of the next few months to get this process off the ground and stable. I think it is very important for SaltStack to get the Windows side of things to a state, where it is trivial for developers to contribute changes without having to worry that they might be breaking things on Windows, when they are mainly interested in the Linux/Unix side of things.

**Comment by obestwalter** [comment]
Abandoned this workflow long ago. There seems to be no one interested or working on it, so closing.
