### ISSUE TITLE
Question: pywin32 vs pypiwin32?

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt-windows-dev#13]
Just curious, any particular reason pywin32.exe was chosen over the pypiwin32 packages that install nicely via pip? I setup a salt env with salt-windows-dev, then uninstalled pywin32 and replaced it with pypiwin32 and everything seemed to work fine.

https://pypi.python.org/pypi/pypiwin32/

**Comment by twangboy** [comment]
At the time I was having a hard time getting them to compile on windows. I haven't checked recently.

**Comment by twangboy** [comment]
I'd rather not depend on an external build. I'll try that out.

**Comment by twangboy** [comment]
pypiwin32 is now in the develop branch instead of the .exe
