### ISSUE TITLE
M2Crypto is not installed after ru

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt-windows-dev#19]

**Comment by TheBigBear** [comment]
`salt-call --versions` showed no version for `M2Crypto`

**Comment by twangboy** [comment]
@TheBigBear Which branch are you on? M2Crypto was removed for 2015.8 and beyond.

**Comment by TheBigBear** [comment]
@twangboy, oh ok, sorry I missed that. I am on `2015.8` on this devel machine and just saw the 'missing' version umber for M2Crypto, sorry. My bad.
