### ISSUE TITLE
how do I add "pygit2" and "GitPython" libs to be included by default?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt-windows-dev#23]
@jfindlay or @twangboy ^^^ do either of you know how do I go about including the `pygit2` and `GitPython` libs so that they become std parts of both the `salt-dev environment` and also get bundled in to the 2015.8 Berrylium release RC4 and higher of the `windows salt-minion installer`?

see https://github.com/saltstack/salt/issues/26158 and https://github.com/saltstack/salt/issues/26461 and https://github.com/saltstack/salt/issues/26460 and https://github.com/saltstack/salt/pull/26422

Do I 'simply' (might need some help/instructions!) do a PR with python 2.7.8 `whl` pkgs for the `32` and `64` dirs? And the rest will just happen "auto-magically"?

BTW how do the files in the `repo.saltstack.com/windows/dependencies` relate to the files in the `32` and `64` subdirectories of it? I can't quite see how the `dev_env.ps1 + dev_env_salt.ps1` files choose exactly what `*.whl` and `*.exe` files to install and what to leave out?

How do I create the correct python `whl` pkgs to be bundled in with the saltstack stock python release?

**Comment by TheBigBear** [comment]
This all only comes to fruition once Erik Johnsons PR https://github.com/saltstack/salt/pull/26541 is actually merged into the 2015.8 branch, of course.

**Comment by TheBigBear** [comment]
So for `pygit2` for `32` and `64` directory there is a corresponfing `whl` file available from:
"http://www.lfd.uci.edu/~gohlke/pythonlibs/" :

```
http://www.lfd.uci.edu/~gohlke/pythonlibs/3i673h27/pygit2-0.21.3-cp27-none-win32.whl
http://www.lfd.uci.edu/~gohlke/pythonlibs/3i673h27/pygit2-0.21.3-cp27-none-win_amd64.whl
```

And for the `GitPython` one a simple `"pip install GitPython"` , should suffice, right? 
But how do I get those into the default `salt-dev` environment and also into the `RC4 of 2015.8.0rc4` and onwards?

**Comment by TheBigBear** [comment]
@twangboy @terminalmage OK. so we discussed this and I officially withdraw this request. ;-)

For the record basically there are licensing concerns that prevent this from being part and parcel of the stock salt tools. (there are many and various licenses involved and none of them are Apache ones)

I will likely work on a `winrepo-ng` python libs installer, that can then handle these 2 python libs, but that is just another way of making it easy for these python libs to be made available for windows minions.

But this issue about pygit2 and GitPython libs to be included can be closed now.

**Comment by twangboy** [comment]
@TheBigBear We could probably do GitPython as it is BSD licensed. It depends on gitDB and smmap which are also both BSD licensed. pygit2 however is gpl, so we can't include that one.
What do you think @UtahDave ?

**Comment by TheBigBear** [comment]
@twangboy it really isn't that big of a deal, I don't think. it will be fairly straight forward (and painless I hope) to get those done as simple user installs.

BTW the pygit2 is GPL, correct, but it does have the linking exclusion, not sure this woudl be good enough? But anyway, as I already said I really don't think this is important enough to worry too much about it. 

Having them as user choosen installs might be a whole lot more straight forward and less prone to controversies.
